### PR TITLE
Delete .babelrc

### PR DESCRIPTION
**Pull request by m0ngr31**
Causes errors on React Native 0.21.0

### CODE REVIEW

**Comment by mlegenhausen** [comment]
What errors does it produce? Wouldn't it be enough to add it to a `.npmignore` file?

**Comment by m0ngr31** [comment]
`Couldn't find preset "es2015"` if I do an `npm install babel-preset-es2015 --save`, I get a `babelhelpers.typeof` issue.

**Comment by mlegenhausen** [comment]
Does it work when you remove the `.babelrc` file from the project installed in node_modules?

**Comment by m0ngr31** [comment]
Removing my own `.babelrc` doesn't, but removing the project one does.

**Comment by mlegenhausen** [comment]
Could you add `"ignore": ["node_modules/**"]` to your `.babelrc` file?

**Comment by m0ngr31** [comment]
This is what I get when I add that line:

```
C:\Dev\ec_app\node_modules\react-native\local-cli\bundle\buildBundle.js:17
function buildBundle(args, config, output = outputBundle) {
                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (C:\Dev\ec_app\node_modules\babel-register\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Dev\ec_app\node_modules\babel-register\lib\node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Dev\ec_app\node_modules\react-native\local-cli\bundle\bundle.js:11:21)
    at Module._compile (module.js:425:26)
```

**Comment by mlegenhausen** [comment]
Try `"ignore": ["node_modules/fetch-intercept/**"]`.

**Comment by m0ngr31** [comment]
Goes back to the `Couldn't find preset "es2015"` I was getting earlier

**Comment by marcusmotill** [comment]
Can this please get addressed.  Same issue here

**Comment by mlegenhausen** [comment]
Please try out version 2.2.1

**Pull request closed without merging**
